import { StyleSheet } from 'react-native';
import { Dimensions } from 'react-native';
export const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingBottom: 40,
  },
  upperContainer: {flex: 1, backgroundColor: 'black'},
  headerTitleView: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    padding: 5,
    marginRight: 10,
  },
  trendingImageView: {
    position: 'relative',
    width: Dimensions.get('screen').width / 5,
    height: Dimensions.get('screen').height / 6,
    justifyContent: 'center',
    marginHorizontal: 10,
    marginVertical: 20,
    alignItems: 'center',
  },
  trendingImage: {
    width: '100%',
    height: '100%',
    borderRadius: 10,
  },
  titleRatingView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    flex: 1,
    margin: 4,
  },
  titleTextView: {width: '50%'},
  cardTitleText: {
    color: 'white',
    fontSize: 20,
    fontWeight: 'bold',
    textTransform: 'capitalize',
  },
  cardImage: {
    width: '100%',
    height: 500,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
  },
  ratingView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: 'rgba(52, 52, 52, 0.8)',
    padding: 6,
    borderRadius: 10,
    // margin: 4,
  },
  uaTextView: {flexDirection: 'row', alignItems: 'center', marginBottom: 5},
  uAtext: {
    fontSize: 14,
    color: '#FAF3F3',
    marginHorizontal: 5,
    fontWeight: 'bold',
  },
  aText: {
    fontWeight: 'bold',
    fontSize: 14,
    color: '#FAF3F3',
    marginLeft: 10,
  },
  voteAverageText: {
    color: 'white',
    fontSize: 13,
    fontWeight: 'bold',
    margin: 5,
  },
  footerView: {
    position: 'absolute',
    backgroundColor: '#2B2B2B',
    left: 0,
    right: 0,
    bottom: 0,
    // top:0,
    width: '100%',
    height: '7%',
    // opacity:0.7,
    alignItems: 'center',
    justifyContent: 'center',
  },
  languageText: {
    fontSize: 14,
    color: '#EEEEEE',
    marginLeft: 10,
    fontWeight: 'bold',
  },
  titleText: {
    margin: 10,
    color: 'white',
    fontWeight: 'bold',
    textTransform: 'uppercase',
    fontSize: 20,
  },
  headerTitleText: {fontWeight: 'bold', color: 'white', fontSize: 18},
});
